namespace SESEWebsite.Models.Enum
{
    public enum Programs
    {
 GENERAL_ENGLISH,
 BASIC_ENGLISH,
 SPOKEN_ENGLISH,
GRAMMATICAL_ENGLISH,
CONVERSATIONAL_ENGLISH,
GENERAL_MATHEMATICS,
FURTHER_MATHEMATICS

    }
}
